# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2ac946fc05fdfe05f7b42292aa8d3572c58be56da2ff1e5a7192fe6b304ad62adcf0724a46f9f9e5630ea09fce75455a1b893755033c0fbdf53d1cee17924db8

test:
  secret_key_base: c40ab15eb1b95ade2232ad1f00c919f8190830434e59734f082003fca3edb47db5abe219d1c370addf50e2864ec29b0d3326e7f2407f7849a1005139ad53d86b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
